stages:
    - build
    - test_build
    - test
      
before_script:
  - mkdir -p ~/lib/dd_avx
  - export LD_LIBRARY_PATH=~/lib/dd_avx

###################################################

build_lib:
    stage: build
    tags:
        - hishinuma-ci
    script:
        - make
        - ls
        - ls lib/
        - ls include/qd/
    artifacts:
        paths:
            - include/
            - lib/
        expire_in: 1day

install_lib:
    stage: install
    tags:
        - hishinuma-ci
    script:
        - make install
    dependencies:
        - "build_lib"
    artifacts:
        paths:
            - ~/lib/dd_avx/
        expire_in: 1day

###################################################

test_build:
    stage: test_build
    tags:
        - hishinuma-ci
    script:
        - cd test; make;
    artifacts:
        paths:
            - test/
        expire_in: 1day

###################################################

test_run:
    stage: test
    tags:
        - hishinuma-ci
    script:
        - cd test; test run;
    artifacts:
        paths:
            - test_build/
        expire_in: 1day
