stages:
    - build
    - test
      
build:
    stage: build
    tags:
        - hishinuma-ci
    script:
        - make
        - ls
        - ls lib/
        - ls lib/qd
        - ls include/qd/
    artifacts:
        paths:
            - include/
            - lib/
        expire_in: 1day

test:
    stage: test
    tags:
        - hishinuma-ci
    script:
        - cd test; make
    dependencies:
        - "build"
