stages:
    - build
    - install
    - build_test
    - run_test_scalar
    - run_test_vector
    - doc
      
before_script:
  - mkdir -p ~/lib/dd_avx
  - export LD_LIBRARY_PATH=~/lib/dd_avx

###################################################

build_lib:
    stage: build
    tags:
        - hishinuma-ci
    script:
        - make
        - ls
        - ls lib/
        - ls include/qd/
    artifacts:
        paths:
            - include/
            - lib/
        expire_in: 1day

###################################################

install_lib:
    stage: install
    tags:
        - hishinuma-ci
    script:
        - make install
    dependencies:
        - "build_lib"
    artifacts:
        paths:
            - ~/lib/dd_avx/
        expire_in: 1day

###################################################

test_build:
    stage: build_test
    tags:
        - hishinuma-ci
    script:
        - cd test; make clean; make
    dependencies:
        - "install_lib"
    artifacts:
        paths:
            - test/
        expire_in: 1day

###################################################

scalar:
    stage: run_test_scalar
    tags:
        - hishinuma-ci
    script:
        - cd test; make run_scalar;
    artifacts:
        paths:
            - test_build/
        expire_in: 1day

###################################################

std:
    stage: run_test_vector
    tags:
        - hishinuma-ci
    script:
        - cd test; ./check.sh std;
    artifacts:
        paths:
            - test_build/
        expire_in: 1day

copy:
    stage: run_test_vector
    tags:
        - hishinuma-ci
    script:
        - cd test; ./check.sh copy;
    artifacts:
        paths:
            - test_build/
        expire_in: 1day
        
add:
    stage: run_test_vector
    tags:
        - hishinuma-ci
    script:
        - cd test; ./check.sh add;
    artifacts:
        paths:
            - test_build/
        expire_in: 1day
###################################################

make_doc:
    stage: doc
    tags:
        - hishinuma-ci
    script:
        - rm -rf /public/dd_avx/
        - cd doc/; doxygen ./Doxyfile; cd -
        - mv doc/html /public/dd_avx
